# >>> IF YOU CHANGE CONFIG RESTART SERVER: "⌃C + bundle exec jekyll serve" <<<

# 1. Build
# 2. Collections
# 3. Front Matter
# 4. Plugins
# 5. Variables

# BUILD ==================================================

## Server (localhost)
port: 4003

## Warnings
strict_front_matter: true
liquid:
  error_mode: strict

## Final _site
exclude:
  - README.md
  - Gemfile.lock # jekyll
  - Gemfile
  - /vendor
  - /docker-compose.yml # docker
  - /docker-start
  - config.codekit3 # codekit3
  - cache
  - log
  - logs
  - node_modules
  - /storage/framework/sessions

# COLLECTIONS ==================================================

## Docs
collections:
  docs:
    permalink: /:collection/:path/
    output: true # render .MD files to HTML on build

# FRONT MATTER ==================================================

## Settings
defaults:
  -
    scope:
      path: "" # empty string means all files in the project
      type: "pages" # select pages only
    values:
      layout: "page"
      lang: "en"
  -
    scope:
      path: "_docs"
      type: "docs" # created in collections
    values:
      layout: "article"
      lang: "en"
      custom_title: null # add custom title variable in docs article if needed

## Conversion
permalink: pretty
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true # disable Rouge highliter
  parse_block_html: true # in .MD files render MD inside HTML blocks

# PLUGINS ==================================================

## Github --safe
plugins:
  - jemoji

# VARIABLES ==================================================

## Site variables
title: "Smartlook API"
google_analytics: "UA-XXXXX-Y"
github_username: smartlook
git_repo: smartlook.github.io

## Custom variables
# (add if needed)

## Product
pr_author: "Smartsupp"
pr_name: "Smartlook"
pr_url: "https://www.smartlook.com/"
pr_url_name: "Smartlook.com"
pr_email: "info@smartlook.com"
pr_description: "Smartlook API. Developer DOCS."

## Url
url_docs_root: "/docs/"

## Pages
pa_github: "Smartlook GitHub"
pa_docs: "Docs"

## Categories
ca_web: "WEB"
ca_sdk: "SDK"

## Categories (descreption)
ca_d_web: "Smartlook JavaScript API offers a number of extra features to make your recordings even better."
ca_d_sdk: "Smartlook SDK gives you the ability to record your native mobile apps."

### Categories (URL)
ca_url_web: "/docs/web/"
ca_url_sdk: "/docs/sdk/"